### ISSUE TITLE
メールアドレスが公開されることに言及する

### ISSUE THREAD

**Issue by HiroKoni** [tsukurobo/Git_workshop#2]
コミットに紐づけられている`user.email` のメールアドレスは、GitHubでリポジトリをpublicにすると公開されますが、このことについて言及を入れておいた方がいい気がします。
対応としては、GitHubの提供する`noreply`メールアドレスを設定するのがメジャーかと。

**Comment by Neko2234** [comment]
ありがとう。
メールアドレスが公開されることについて言及するようにしたプルリクエストを作成したので時間あれば見てもらえると助かります。
